version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  mysql:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DB=mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  node-app:
    build: ./
    image: node-app:1.0
    working_dir: /home/node/app
    environment:
        - NODE_ENV=production
    volumes:
        - ./:/home/node/app
    ports:
       - '9999:9999'
    command: "npm start"